language: bash
services: docker
env:
  matrix:
    - VERSION=1.27
    - VERSION=1.26
    - VERSION=1.25
    - VERSION=1.24.1
script:
  - ./docker-tool.sh build $VERSION
  - ./docker-tool.sh test $VERSION
